### ISSUE TITLE
about spleen dataset

### ISSUE THREAD

**Issue by GuobinZhangTJU** [DanielY1783/cs8395_final_project#1]
Hi, thanks for your sharing. I want to ask you for help. Can you provide the link of spleen dataset used in this work? Many thanks~

**Comment by DanielY1783** [comment]
Hi, please see https://www.synapse.org/#!Synapse:syn3193805/wiki/89480
You can get just the spleen labels with a simple filter of the labels.

**Comment by GuobinZhangTJU** [comment]
> Hi, please see https://www.synapse.org/#!Synapse:syn3193805/wiki/89480
> You can get just the spleen labels with a simple filter of the labels.

Thanks for your reply, the images are MRI in the link?

**Comment by DanielY1783** [comment]
Yeah, I think they should be in MRI.

**Comment by DanielY1783** [comment]
Original question should be answered
